### ISSUE TITLE
Analysis that requires keyring: Modules do not initialise with the keyring package

### ISSUE THREAD

**Issue by DrTTrousers** [OHDSI/Strategus#26]
`• start target CohortGeneratorModule_1
Error in loadNamespace(x) : there is no package called ‘keyring’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
• built target CohortGeneratorModule_1 [3.069 seconds]
• start target PatientLevelPredictionModule_2
Error in loadNamespace(x) : there is no package called ‘keyring’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted`

When running a script, the analysis specifications creates these two modules. The respective module renv lockfiles do not call the keyring package by default, causing the above error. 

Modifying the lockfile to call keyring does not result in it being loaded either, above error.

Entering each module and restoring the lockfile into that project specifically calling keyring does not work either. Above error.

RStudio workbench on Linux environment, Keyring works as expected otherwise and is installed into the base library.

**Comment by anthonysena** [comment]
Thanks @DrTTrousers for reporting this issue. Strategus will load `keyring` when executing a module so the module itself should not need to declare the dependency in the renv.lock file. That said, it seems that the kerying dependency is missing for some reason which I suspect may be related to #25.

**Comment by DrTTrousers** [comment]
@anthonysena I'd just like to follow up on this: I installed RStudio on a local windows environment yesterday and ran the same script as originally provided, other than a few Rstudio specific teething issues and having to update some of the lockfile references to things that are no longer on CRAN, the package ran as expected.

Therefore this keyring thing seems to be a linux specific issue. Potentially as the keyring needs unlocking for each client process?

**Comment by DrTTrousers** [comment]
@anthonysena follow up to the follow up!

The local windows install is now showing the corrupt library issue you mention in #25
I was attempting a new run with a different version of the same base script and encountered the corruption.

**Comment by anthonysena** [comment]
Thanks for the updates @DrTTrousers. Regarding keyring: I need to expose more of the keyring specific configuration options that are available in that base package for non-Windows users so hoping that helps. Timing of that is this week (hopefully). 

As for the corrupted libraries: I need to see if there is a way to perform an renv::restore() without touching the base libraries. 

If you have any ideas on these items based on your experience, please feel free to share and thanks!

**Comment by anthonysena** [comment]
@DrTTrousers - The branch `issue-24-keyring` aims to add more flexibility for using keyring on non-Windows systems. The functions for storing & retrieving connection details for your CDM allow for specifying the keyring name & password and this information is then used by Strategus when executing each module.

**Comment by anthonysena** [comment]
Thanks @DrTTrousers - I'd appreciate your feedback. One thing that would be useful to test and perhaps confirm: on Linux, can you manually unlock a keyring prior to calling Strategus so that the password is not required? I'd like to avoid the need to have Strategus obtain the password for keyring if possible so I may modify the current branch to check if a named keyring is locked and if so, we'd stop processing so the user can unlock it before executing.

**Comment by anthonysena** [comment]
@DrTTrousers - I believe the relevant fixes have been applied to the `develop` branch and will be part of the next release. I'll close this out but please re-open if you are still facing these issues. Thanks!

**Comment by DrTTrousers** [comment]
Apologies @anthonysena, I only got round to re-running the package with the develop update yesterday.

The issue remains:

`Connecting using Redshift driver
• start target analysisSpecifications                                                                                                                                                          
• built target analysisSpecifications [1.084 seconds]
• start target executionSettings
• built target executionSettings [0.003 seconds]
• start target CohortGeneratorModule_1
Error in b__file_set_keyring_pass(self, private, key, keyring) : 
  Aborted setting keyring password
Calls: <Anonymous> ... b_file_keyring_unlock -> <Anonymous> -> b__file_set_keyring_pass
Execution halted
✖ error target CohortGeneratorModule_1
• end pipeline [2.486 seconds]
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: Module did not complete. To debug:
  rstudioapi::openProject('{snipped}Output/StrategusInstantiatedModules/CohortGeneratorModule_0.0.13', newSession = TRUE)
  file.edit('{snipped}Output/strategusWork/CohortGeneratorModule_1/StrategusScript.R')`

Inside each module Renv, Keyring does not exist, so it doesn't appear to attach properly, which is very strange.

Furthermore, using the {Keyring} functions, keyring_is_locked() and keyring_unlock() work from the console, but I think what occurs is each subsequent process that is initiated becomes its own anonymous process, so it won't connect to the same keyring.

I am uncertain how to proceed with debugging. I was, once again, able to execute the same script without issue on a local windows instance. I will get back to looking into this as I have time. Perhaps we should leave this issue open for the time being while I keep looking at it?

I will also make all efforts to attend more HADES meetings as I'm finding all sorts of issues elsewhere at the moment.

**Comment by anthonysena** [comment]
Thanks @DrTTrousers for the notes here and for giving this a try. Unfortunately I'm flying blind here in that I only run Windows as the moment.

Just to make a few notes on your comments above:

> Inside each module's Renv (CohortGenerator, PLP @jreps), Keyring does not exist, so it doesn't appear to attach properly, which is very strange.

That's correct since Strategus does this when a module is instantiated as shown here:

https://github.com/OHDSI/Strategus/blob/01e63f7b160801c012a48dedbc432f1c55a9cfc6/R/ModuleInstantiation.R#L161-L178

Additionally `keyring` is noted in the `Imports` field of Strategus. Given the errors you have noted above, it would appear that keyring is installed as it is able to invoke package methods and then receive the errors. 

From your original post, I'm noting the following:

> RStudio workbench on Linux environment, Keyring works as expected otherwise and is installed into the base library.

I'm wondering if you could share your sessionInfo() to just see the configuration? In addition, the new updates I've made to the develop branch, I was wondering if you could try the following script:

``` r
allKeyrings <- keyring::keyring_list()
if (!"strategus" %in% allKeyrings$keyring) {
  keyring::keyring_create(keyring = "strategus", password = "foobar")
}
# Lock it
keyring::keyring_lock(keyring = "strategus")
# List the keyrings
keyring::keyring_list()
#>     keyring num_secrets locked
#> 1                    21  FALSE
#> 2    system           0   TRUE
#> 3 strategus           1   TRUE

# Use keyring to store the connection details securely
# using a named and secured keyring
connectionDetails <- Eunomia::getEunomiaConnectionDetails(
  databaseFile = "C:/strategus/cdm.sqlite"
)
Sys.setenv("STRATEGUS_KEYRING_PASSWORD"="foobar")
Strategus::storeConnectionDetails(connectionDetails = connectionDetails,
                                  connectionDetailsReference = "eunomia",
                                  keyringName = "strategus")


# Use Strategus to unlock the keyring & get the secret
status <- Strategus::unlockKeyring(keyringName = "strategus")
Sys.setenv("STRATEGUS_KEYRING_PASSWORD"="foobar")
keyring::key_get(service = "eunomia", keyring = "strategus")
#> [1] "{\n  \"dbms\": \"sqlite\",\n  \"extraSettings\": null,\n  \"oracleDriver\": \"thin\",\n  \"pathToDriver\": \"C:/jdbcDrivers\",\n  \"user\": \"\",\n  \"password\": \"\",\n  \"server\": \"C:/strategus/cdm.sqlite\",\n  \"port\": \"\",\n  \"connectionString\": \"\",\n  \"attr_class\": \"connectionDetails\"\n}"
```

<sup>Created on 2023-01-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DrTTrousers** [comment]
Sure, sessioninfo()
``` r
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=C.UTF-8          LC_NUMERIC=C              LC_TIME=C.UTF-8           LC_COLLATE=C.UTF-8        LC_MONETARY=C.UTF-8      
 [6] LC_MESSAGES=C.UTF-8       LC_PAPER=C.UTF-8          LC_NAME=C.UTF-8           LC_ADDRESS=C.UTF-8        LC_TELEPHONE=C.UTF-8     
[11] LC_MEASUREMENT=C.UTF-8    LC_IDENTIFICATION=C.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keyring_1.3.1           Strategus_0.0.3         CohortGenerator_0.7.0   DatabaseConnector_5.1.0

loaded via a namespace (and not attached):
 [1] rstudioapi_0.14      magrittr_2.0.3       tidyselect_1.2.0     bit_4.0.5            R6_2.5.1             rlang_1.0.6          fansi_1.0.4         
 [8] dplyr_1.0.10         tools_4.2.1          utf8_1.2.2           cli_3.6.0            DBI_1.1.3            bit64_4.0.5          assertthat_0.2.1    
[15] tibble_3.1.8         lifecycle_1.0.3      rJava_1.0-6          ParallelLogger_3.1.0 vctrs_0.5.1          glue_1.6.2           compiler_4.2.1      
[22] pillar_1.8.1         generics_0.1.3       renv_0.16.0          pkgconfig_2.0.3     
```

And the output from your reprex, demonstrates the same error we see inside the package:

``` r
allKeyrings <- keyring::keyring_list()
if (!"strategus" %in% allKeyrings$keyring) {
  keyring::keyring_create(keyring = "strategus", password = "foobar")
}
# Lock it
keyring::keyring_lock(keyring = "strategus")
# List the keyrings
keyring::keyring_list()
#>     keyring num_secrets locked
#> 1 strategus           0   TRUE
#> 2    system           1   TRUE


# Use keyring to store the connection details securely
# using a named and secured keyring
connectionDetails <- Eunomia::getEunomiaConnectionDetails()

Sys.setenv("STRATEGUS_KEYRING_PASSWORD"="foobar")
Strategus::storeConnectionDetails(connectionDetails = connectionDetails,
                                  connectionDetailsReference = "eunomia",
                                  keyringName = "strategus")
#> Error in Strategus::storeConnectionDetails(connectionDetails = connectionDetails, : unused argument (keyringName = "strategus")


# Use Strategus to unlock the keyring & get the secret
status <- Strategus::unlockKeyring(keyringName = "strategus")
#> Error: 'unlockKeyring' is not an exported object from 'namespace:Strategus'
Sys.setenv("STRATEGUS_KEYRING_PASSWORD"="foobar")
keyring::key_get(service = "eunomia", keyring = "strategus")
#> Error in b__file_set_keyring_pass(self, private, key, keyring): Aborted setting keyring password
```

<sup>Created on 2023-01-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by anthonysena** [comment]
Thanks @DrTTrousers for sharing this information - it is helpful. The errors shown in the reprex above indicate to me that you may not have installed the latest version of Strategus (please use the develop branch). The `keyringName` argument in the `storeConnectionDetails` function should be available on that branch along with the function `unlockKeyring` which are likely missing due to an older build of Strategus. 

When you have an opportunity, could you reinstall Strategus (`remotes::install_github("OHDSI/Strategus", ref="develop")`) and try the test code again? Thanks!

**Comment by DrTTrousers** [comment]
@anthonysena Here you go

``` r
remotes::install_github("OHDSI/Strategus", ref="develop")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'Strategus' from a github remote, the SHA1 (4a8e47d5) has not changed since last install.
#>   Use `force = TRUE` to force installation

allKeyrings <- keyring::keyring_list()
if (!"strategus" %in% allKeyrings$keyring) {
  keyring::keyring_create(keyring = "strategus", password = "foobar")
}
# Lock it
keyring::keyring_lock(keyring = "strategus")
# List the keyrings
keyring::keyring_list()
#>     keyring num_secrets locked
#> 1 strategus           0   TRUE
#> 2    system           1   TRUE


# Use keyring to store the connection details securely
# using a named and secured keyring
connectionDetails <- Eunomia::getEunomiaConnectionDetails()

Sys.setenv("STRATEGUS_KEYRING_PASSWORD"="foobar")
Strategus::storeConnectionDetails(connectionDetails = connectionDetails,
                                  connectionDetailsReference = "eunomia",
                                  keyringName = "strategus")


# Use Strategus to unlock the keyring & get the secret
status <- Strategus::unlockKeyring(keyringName = "strategus")
Sys.setenv("STRATEGUS_KEYRING_PASSWORD"="foobar")
keyring::key_get(service = "eunomia", keyring = "strategus")
#> [1] "{\n  \"dbms\": \"sqlite\",\n  \"extraSettings\": null,\n  \"oracleDriver\": \"thin\",\n  \"pathToDriver\": \"/home/jbrewster/drivers\",\n  \"user\": \"\",\n  \"password\": \"\",\n  \"server\": \"/data/Rtmpsjzbst/file107dd67c527c67.sqlite\",\n  \"port\": \"\",\n  \"connectionString\": \"\",\n  \"attr_class\": \"connectionDetails\"\n}"
```

<sup>Created on 2023-01-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DrTTrousers** [comment]
Good (?) news! Keyring now behaves itself.

However, referring back to the original error that brought me to this issue in Dec (copied below for reference):
``` r
start target CohortGeneratorModule_1 Error in loadNamespace(x) : there is no package called ‘keyring’ Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart Execution halted
built target CohortGeneratorModule_1 [3.069 seconds] 
start target PatientLevelPredictionModule_2 Error in loadNamespace(x) : there is no package called ‘keyring’ Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart Execution halted
```

As you can see, we started building the modules with the previous version.
In the new version, after the Keyring issue has been solved, we get a similar error, this time referring to Strategus itself:

``` r
start target CohortGeneratorModule_1
Error in loadNamespace(x) : there is no package called ‘Strategus’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
✖ error target CohortGeneratorModule_1
• end pipeline [2.355 seconds]
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: Module did not complete. To debug:
  rstudioapi::openProject('~/pioneer-studyathon-1/V1/Output_BDM/StrategusInstantiatedModules/CohortGeneratorModule_0.0.14', newSession = TRUE)
  file.edit('~/pioneer-studyathon-1/V1/Output_BDM/strategusWork/CohortGeneratorModule_1/StrategusScript.R')
```

Perhaps the same fix could correct for this?

**Comment by anthonysena** [comment]
Thanks @DrTTrousers for your continued patience and persistence here. 

For reference, I'm going to copy in the code that is in the StrategusScript.R for the CohortGeneratorModule_1 based on a local run I have:

```r
source('Main.R')
jobContext <- readRDS("c:/strategus/EunomiaTestStudy/work_folder/CohortGeneratorModule_1/jobContext.rds")

# If the keyring is locked, unlock it, set the value and then re-lock it
keyringLocked <- Strategus::unlockKeyring(keyringName = jobContext$keyringSettings$keyringName)
connectionDetails <- keyring::key_get(jobContext$moduleExecutionSettings$connectionDetailsReference, keyring = jobContext$keyringSettings$keyringName)
                   connectionDetails <- ParallelLogger::convertJsonToSettings(connectionDetails)
                   connectionDetails <- do.call(DatabaseConnector::createConnectionDetails, connectionDetails)
                   jobContext$moduleExecutionSettings$connectionDetails <- connectionDetails
if (keyringLocked) {
  keyring::keyring_lock(keyring = jobContext$keyringSettings$keyringName)
}

ParallelLogger::addDefaultFileLogger(file.path(jobContext$moduleExecutionSettings$resultsSubFolder, 'log.txt'))
ParallelLogger::addDefaultErrorReportLogger(file.path(jobContext$moduleExecutionSettings$resultsSubFolder, 'errorReport.R'))

options(andromedaTempFolder = file.path(jobContext$moduleExecutionSettings$workFolder, 'andromedaTemp'))

if (Sys.getenv('FORCE_RENV_USE', '') == 'TRUE') {
  renv::use(lockfile = 'renv.lock')
}
execute(jobContext)

ParallelLogger::unregisterLogger('DEFAULT_FILE_LOGGER', silent = TRUE)
ParallelLogger::unregisterLogger('DEFAULT_ERRORREPORT_LOGGER', silent = TRUE)
writeLines('done', file.path(jobContext$moduleExecutionSettings$resultsSubFolder, 'done'))
```

I suspect the line `keyringLocked <- Strategus::unlockKeyring(keyringName = jobContext$keyringSettings$keyringName)` is causing the issue here....since this is not a package that we require to be in the renv cache (unlike keyring and ParallelLogger). Let me try to revise this on a new branch and if you could test to confirm that closes the issue, that would be great. Thanks and stay tuned.

**Comment by anthonysena** [comment]
OK @DrTTrousers I've pushed a branch which you can install using `remotes::install_github("OHDSI/Strategus", ref="issue-26-module-keyring")` which I'm hoping works well for you. :grinning:

**Comment by DrTTrousers** [comment]
Hi @anthonysena, It still doesn't like it on the Workbench. 

``` r
remotes::install_github("OHDSI/Strategus", ref="issue-26-module-keyring", force = TRUE)
...
** testing if installed package keeps a record of temporary installation path
* DONE (Strategus)
> source("~/V1/CodeToRun/CodeToRunBigDataModel.R")
Connecting using Redshift driver
• start target analysisSpecifications                                                                                                                                                           
• built target analysisSpecifications [0.995 seconds]
• start target executionSettings
• built target executionSettings [0.003 seconds]
• start target keyringSettings
• built target keyringSettings [0.003 seconds]
• start target CohortGeneratorModule_1
Error in loadNamespace(x) : there is no package called ‘Strategus’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
✖ error target CohortGeneratorModule_1
• end pipeline [2.292 seconds]
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: Module did not complete. To debug:
  rstudioapi::openProject('~/pioneer-studyathon-1/V1/Output_BDM/StrategusInstantiatedModules/CohortGeneratorModule_0.0.14', newSession = TRUE)
  file.edit('~/V1/Output_BDM/strategusWork/CohortGeneratorModule_1/StrategusScript.R')
```

StrategusScript contents below as well, in case that helps

``` r

    source('Main.R')
    jobContext <- readRDS("~/V1/Output_BDM/strategusWork/CohortGeneratorModule_1/jobContext.rds")

    # If the keyring is locked, unlock it, set the value and then re-lock it
    keyringName <- jobContext$keyringSettings$keyringName
    keyringLocked <- Strategus::unlockKeyring(keyringName = keyringName)
    if (keyringLocked) {
        keyring::keyring_unlock(keyring = keyringName, password = Sys.getenv('STRATEGUS_KEYRING_PASSWORD'))
    }
  connectionDetails <- keyring::key_get(jobContext$moduleExecutionSettings$connectionDetailsReference, keyring = jobContext$keyringSettings$keyringName)
                       connectionDetails <- ParallelLogger::convertJsonToSettings(connectionDetails)
                       connectionDetails <- do.call(DatabaseConnector::createConnectionDetails, connectionDetails)
                       jobContext$moduleExecutionSettings$connectionDetails <- connectionDetails
    if (keyringLocked) {
      keyring::keyring_lock(keyring = jobContext$keyringSettings$keyringName)
    }

    ParallelLogger::addDefaultFileLogger(file.path(jobContext$moduleExecutionSettings$resultsSubFolder, 'log.txt'))
    ParallelLogger::addDefaultErrorReportLogger(file.path(jobContext$moduleExecutionSettings$resultsSubFolder, 'errorReport.R'))

    options(andromedaTempFolder = file.path(jobContext$moduleExecutionSettings$workFolder, 'andromedaTemp'))

    if (Sys.getenv('FORCE_RENV_USE', '') == 'TRUE') {
      renv::use(lockfile = 'renv.lock')
    }
    execute(jobContext)

    ParallelLogger::unregisterLogger('DEFAULT_FILE_LOGGER', silent = TRUE)
    ParallelLogger::unregisterLogger('DEFAULT_ERRORREPORT_LOGGER', silent = TRUE)
    writeLines('done', file.path(jobContext$moduleExecutionSettings$resultsSubFolder, 'done'))
```

I can also confirm that the script works as expected (still) with the updated package on my Windows Local.

**Comment by anthonysena** [comment]
Thanks @DrTTrousers for sharing these details. I found the issue and will update you when I have the fix confirmed.

**Comment by anthonysena** [comment]
@DrTTrousers - an update here. I've pushed an update to the `develop` branch (install using `remotes::install_github("OHDSI/Strategus", ref="develop")`) that I'm hopeful will fix your issue.

To summarize what has changed: we found that some of the Strategus modules had some structural issues that were causing renv problems when restoring the dependencies. We've updated the various modules to address this issue and things should be stable. Next, I've added an explicit dependency for `keyring` to the underlying target script which should allow Strategus to find the `keyring` package and unlock/re-lock the keyring as necessary.

Would you mind checking that the script below works for you? Just to note: this script will use the `analysisSpecification.json` embedded in Strategus which references the newer versions of the modules. 

```r

# Create a keyring called "strategus" that is password protected
allKeyrings <- keyring::keyring_list()
if (!"strategus" %in% allKeyrings$keyring) {
  keyring::keyring_create(keyring = "strategus", password = "foobar")
}
# Lock the keyring
keyring::keyring_lock(keyring = "strategus")

# Store the connection details
connectionDetails <- Eunomia::getEunomiaConnectionDetails(
  databaseFile = "C:/strategus/cdm.sqlite"
)

# Using a named and secured keyring
Sys.setenv("STRATEGUS_KEYRING_PASSWORD"="foobar")
Strategus::storeConnectionDetails(connectionDetails = connectionDetails,
                                  connectionDetailsReference = "eunomia",
                                  keyringName = "strategus")

Sys.setenv("INSTANTIATED_MODULES_FOLDER" = "c:/strategus/modules")
analysisSpecifications <- ParallelLogger::loadSettingsFromJson(
  fileName = system.file("testdata/analysisSpecification.json",
                         package = "Strategus")
)

executionSettings <- createCdmExecutionSettings(
  connectionDetailsReference = "eunomia",
  workDatabaseSchema = "main",
  cdmDatabaseSchema = "main",
  cohortTableNames = CohortGenerator::getCohortTableNames(),
  workFolder = file.path("C:/strategus/EunomiaTestStudy", "work_folder"),
  resultsFolder = file.path("C:/strategus/EunomiaTestStudy", "results_folder"),
  minCellCount = 5
)

if (!dir.exists("C:/strategus/EunomiaTestStudy")) {
  dir.create("C:/strategus/EunomiaTestStudy")
}
ParallelLogger::saveSettingsToJson(
  object = executionSettings,
  file.path("C:/strategus/EunomiaTestStudy", "eunomiaExecutionSettings.json")
)

executionSettings <- ParallelLogger::loadSettingsFromJson(
  fileName = "C:/strategus/EunomiaTestStudy/eunomiaExecutionSettings.json"
)

Strategus::execute(
  analysisSpecifications = analysisSpecifications,
  executionSettings = executionSettings,
  executionScriptFolder = "C:/strategus/EunomiaTestStudy/script_folder",
  keyringName = "strategus"
)
```

**Comment by DrTTrousers** [comment]
@anthonysena Hello, had a quick test of this this morning:

``` r
# Store the connection details
connectionDetails <- Eunomia::getEunomiaConnectionDetails()

# Using a named and secured keyring
Sys.setenv("STRATEGUS_KEYRING_PASSWORD"="foobar")
Strategus::storeConnectionDetails(connectionDetails = connectionDetails,
                                  connectionDetailsReference = "eunomia",
                                  keyringName = "strategus")
```
we error here, it appears there is a typo in the check assert (but reprex doesn't directly capture the error message) here it is from the console:

``` r
Error in source("~/pioneer-studyathon-1/keyringDebuggin2.R") : 
  1 assertions failed:
 * Variable 'connectionDetails': Must inherit from class 'connectionDetails', but has classes
 * 'ConnectionDetails','DefaultConnectionDetails'.
```

I think its this line in the settings.R:
https://github.com/OHDSI/Strategus/blob/e8536102c8bddc26da4088a715955ae78d84241d/R/Settings.R#L197

**Comment by anthonysena** [comment]
Thanks for trying this @DrTTrousers. Can you confirm that you installed the `develop` branch of Strategus? And which version of DatabseConnector you are using? There is code that should handle both DatabaseConnector v5 & v6:

https://github.com/OHDSI/Strategus/blob/e8536102c8bddc26da4088a715955ae78d84241d/R/Settings.R#L194-L198

**Comment by DrTTrousers** [comment]
Hi @anthonysena, I can confirm I am on DatabaseConnector 6.0.0, and using the develop branch of Strategus (apologies about the delay in getting back on this)

Reprex doesn't like doing the script output, so I'll append the full script, followed by the error I get now... which is different today.
``` r
# Latest fix
remotes::install_github("OHDSI/Strategus", ref="develop")

# Latest DatabaseConnector
remotes::install_github("OHDSI/DatabaseConnector")

library(Strategus)
# Create a keyring called "strategus" that is password protected
allKeyrings <- keyring::keyring_list()
if (!"strategus" %in% allKeyrings$keyring) {
  keyring::keyring_create(keyring = "strategus", password = "foobar")
}
# Lock the keyring
keyring::keyring_lock(keyring = "strategus")

# Store the connection details
connectionDetails <- Eunomia::getEunomiaConnectionDetails()

# Using a named and secured keyring
Sys.setenv("STRATEGUS_KEYRING_PASSWORD"="foobar")
Strategus::storeConnectionDetails(connectionDetails = connectionDetails,
                                  connectionDetailsReference = "eunomia",
                                  keyringName = "strategus")

Sys.setenv("INSTANTIATED_MODULES_FOLDER" = paste0(here::here(),"/strategus/modules"))
analysisSpecifications <- ParallelLogger::loadSettingsFromJson(
  fileName = system.file("testdata/analysisSpecification.json",
                         package = "Strategus")
)

executionSettings <- createCdmExecutionSettings(
  connectionDetailsReference = "eunomia",
  workDatabaseSchema = "main",
  cdmDatabaseSchema = "main",
  cohortTableNames = CohortGenerator::getCohortTableNames(),
  workFolder = file.path(paste0(here::here(), "work_folder")),
  resultsFolder = file.path(paste0(here::here(), "results_folder")),
  minCellCount = 5
)

if (!dir.exists(paste0(here::here(),"/EunomiaTestStudy"))) {
  dir.create(paste0(here::here(),"/EunomiaTestStudy"))
}
ParallelLogger::saveSettingsToJson(
  object = executionSettings,
  file.path(paste0(here::here(),"/EunomiaTestStudy/eunomiaExecutionSettings.json"))
)

executionSettings <- ParallelLogger::loadSettingsFromJson(
  fileName = paste0(here::here(),"/EunomiaTestStudy/eunomiaExecutionSettings.json")
)

Strategus::execute(
  analysisSpecifications = analysisSpecifications,
  executionSettings = executionSettings,
  executionScriptFolder = paste0(here::here(),"/EunomiaTestStudy/script_folder"),
  keyringName = "strategus"
)
```

And now the console error:

``` r
• built target keyringSettings [0.003 seconds]
• start target CohortGeneratorModule_1
Error in loadNamespace(x) : there is no package called ‘Strategus’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
✖ error target CohortGeneratorModule_1
• end pipeline [2.669 seconds]
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: Module did not complete. To debug:
  rstudioapi::openProject('/.../strategus/modules/CohortGeneratorModule_0.0.15', newSession = TRUE)
  file.edit('/.../CohortGeneratorModule_1/StrategusScript.R')
Warning messages:
1: In structure(.Call(C_Rmd5, files), names = files) :
  md5 failed on file 'strategus'
2: In structure(.Call(C_Rmd5, files), names = files) :
  md5 failed on file 'strategus'
3: In structure(.Call(C_Rmd5, files), names = files) :
  md5 failed on file 'strategus'
4: In structure(.Call(C_Rmd5, files), names = files) :
  md5 failed on file 'strategus'
```

As you can see, its now complaining about the forwards loading again....

**Comment by anthonysena** [comment]
Thanks @DrTTrousers for trying this out again. Just wanted to confirm with you: when you ran `execute`, did all of the modules initialize properly? To confirm this,  you would have seen a lot of messages from renv as it restored the dependencies and ultimately a folder for each module in: ```Sys.setenv("INSTANTIATED_MODULES_FOLDER" = paste0(here::here(),"/strategus/modules"))```.

In terms of the error `there is no package called ‘Strategus’` I think I found the culprit:

https://github.com/OHDSI/Strategus/blob/e8536102c8bddc26da4088a715955ae78d84241d/R/RunModule.R#L55-L62

I need to revise this to remove the Strategus reference from this script and just use keyring directly. I was trying to avoid duplicating code but having a reference to Strategus in that script feels wrong as it is a circular dependency. I'll let you know when I have a patch for this and hopefully that helps get past this issue.

**Comment by anthonysena** [comment]
@DrTTrousers - ok I put a patch together on this branch:

`remotes::install_github("OHDSI/Strategus", ref="issue-26-keyring")`

To be safe, could you also remove the contents of your modules folder: `Sys.setenv("INSTANTIATED_MODULES_FOLDER" = paste0(here::here(),"/strategus/modules"))` and re-execute your script?

Thank you!

**Comment by DrTTrousers** [comment]
@anthonysena I left this running last night and found it had completed this morning. 

``` r
Validating inputs
Connecting using SQLite driver
  |======================================================================| 100%
Executing SQL took 0.019 secs
  |======================================================================| 100%
Executing SQL took 0.452 secs
  |======================================================================| 100%
Executing SQL took 0.00557 secs
Export data
[1] TRUE
[1] TRUE
• built target CohortIncidenceModule_3 [5.791 seconds]
• end pipeline [10.043 minutes]
Warning messages:
1: In structure(.Call(C_Rmd5, files), names = files) :
  md5 failed on file 'strategus'
2: In structure(.Call(C_Rmd5, files), names = files) :
  md5 failed on file 'strategus'
3: In structure(.Call(C_Rmd5, files), names = files) :
  md5 failed on file 'strategus'
4: In structure(.Call(C_Rmd5, files), names = files) :
  md5 failed on file 'strategus'
```
The results appeared to be there, but to be sure, I started again this morning and got a stop warning much quicker (Starting with empty folders etc.) 

``` r
Error in instantiateModule(module, version, remoteRepo, remoteUsername,  : 
  The module 'SelfControlledCaseSeriesModule' (v0.0.3) is missing the following files required by renv:
- Missing renv dependency 'renv/settings.dcf'
As a result, Strategus cannot use this module as part of the execution pipeline otherwise it may corrupt your R library.
Please check to see if a newer version of this module exists and update your analysis specification to use that module instead.
```

I think this recent patch has fixed the main issue, we need to determine if all the modules are still compliant?

**Comment by anthonysena** [comment]
Thanks for your continued patience here @DrTTrousers. You are correct - the problem you observed above is directly related to some new checks in Strategus that aim to prevent you from using a Strategus module that is missing the necessary renv dependencies (#25). I've now updated the module references in the test `analysisSpecification.json` and have included this work in the `issue-26-keyring`.

If you'd like to re-install that branch and try re-running your tests, I think this should hopefully resolve the issues you've faced here. Thanks again for testing this as it will be a big help to the OHDSI community when they use Strategus!

**Comment by DrTTrousers** [comment]
Test script seems to run fine now with the updated package.

I've taken the liberty of moving ahead to the guniea pig script again now, (finding unrelated issues no less!) but will hopefully be able to close out this issue soon.

Also going forward I'm happy to provide linux env testing if you would like.

**Comment by DrTTrousers** [comment]
``` r
Loading required package: DatabaseConnector
Connecting using SQLite driver
• start target analysisSpecifications                                                                                                                                                                                               
• built target analysisSpecifications [1.088 seconds]
• start target executionSettings
• built target executionSettings [0.004 seconds]
• start target keyringSettings
• built target keyringSettings [0.004 seconds]
• start target CohortGeneratorModule_1
Error in loadNamespace(x) : there is no package called ‘keyring’
Calls: unlockKeyring ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
✖ error target CohortGeneratorModule_1
• end pipeline [2.389 seconds]
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: Module did not complete. To debug:
  rstudioapi::openProject('/strategus/modules/CohortGeneratorModule_0.0.16', newSession = TRUE)
  file.edit('/work_folder/CohortGeneratorModule_1/StrategusScript.R')
Warning messages:
1: In structure(.Call(C_Rmd5, files), names = files) :
  md5 failed on file 'strategus'
2: In structure(.Call(C_Rmd5, files), names = files) :
  md5 failed on file 'strategus'
3: In structure(.Call(C_Rmd5, files), names = files) :
  md5 failed on file 'strategus'
4: In structure(.Call(C_Rmd5, files), names = files) :
  md5 failed on file 'strategus'
```

I take it back @anthonysena, It appeared to have run fine, and now will not run again. I can confirm that this affects both the guinea pig original work and the debugging script. Something appears to have changed in CohortGenerator again? we appear to be back at Keyring issues.

I can also confirm it still works on Windows 😄

**Comment by anthonysena** [comment]
@DrTTrousers - I'm a bit of a loss as to why keyring is not found. I am going to see if I can get access to a Linux environment to test some of this out so that I can debug some of this on my side. In the meantime, I've merged in a branch to remove the Strategus reference when executing each module which helped me on Windows. So, I'll keep this open since it is a known issue.

**Comment by DrTTrousers** [comment]
@anthonysena Checked again today - sorry for the delay
**Linux-** Debug script, develop branch:

``` r
Connecting using SQLite driver
• start target analysisSpecifications                                                                                                                                                                                               
• built target analysisSpecifications [1.682 seconds]
• start target executionSettings
• built target executionSettings [0.005 seconds]
• start target keyringSettings
• built target keyringSettings [0.005 seconds]
• start target CohortGeneratorModule_1
Error in loadNamespace(x) : there is no package called ‘keyring’
Calls: unlockKeyring ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
✖ error target CohortGeneratorModule_1
• end pipeline [3.769 seconds]
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: Module did not complete. To debug:
  rstudioapi::openProject('/strategus/modules/CohortGeneratorModule_0.0.16', newSession = TRUE)
  file.edit('work_folder/CohortGeneratorModule_1/StrategusScript.R')
```

We also get md5 checksum errors (in Linux), but only on invoking the package functions, not loading the library -
``` r
 Strategus::storeConnectionDetails(connectionDetails = connectionDetails,
+                                   connectionDetailsReference = "eunomia",
+                                   keyringName = "strategus")
Warning messages:
1: In structure(.Call(C_Rmd5, files), names = files) :
  md5 failed on file 'strategus'
2: In structure(.Call(C_Rmd5, files), names = files) :
  md5 failed on file 'strategus'
3: In structure(.Call(C_Rmd5, files), names = files) :
  md5 failed on file 'strategus'
4: In structure(.Call(C_Rmd5, files), names = files) :
  md5 failed on file 'strategus'
> Sys.setenv("INSTANTIATED_MODULES_FOLDER" = paste0(here::here(),"/strategus/modules"))
```

This is very strange, as in windows, it doesn't throw md5 check fails
**Windows -** Debug Script, develop branch
``` r
# Store the connection details
> connectionDetails <- Eunomia::getEunomiaConnectionDetails()
> # Using a named and secured keyring
> Sys.setenv("STRATEGUS_KEYRING_PASSWORD"="foobar")
> Strategus::storeConnectionDetails(connectionDetails = connectionDetails,
+                                   connectionDetailsReference = "eunomia",
+                                   keyringName = "strategus")
> Sys.setenv("INSTANTIATED_MODULES_FOLDER" = paste0(here::here(),"/strategus/modules"))
> analysisSpecifications <- ParallelLogger::loadSettingsFromJson(
+   fileName = system.file("testdata/analysisSpecification.json",
+                          package = "Strategus")
+ )
> executionSettings <- createCdmExecutionSettings(....
```

The debug script executes in Windows - but doesn't enjoy trying to find specific binaries anymore, possibly due to the MRAN deprecation?
(Several instances during Renv downloads, a soupçon sequestered subjacent)

``` r
Retrieving 'https://api.github.com/repos/ohdsi/CohortGenerator/tarball/v0.7.0' ...
	OK [downloaded 415.3 Kb in 1.6 secs]
* Querying repositories for available binary packages ... Done!
* Querying repositories for available source packages ... Done!
Warning: failed to find binary for 'dplyr 1.0.8' in package repositories
Warning: failed to find source for 'dplyr 1.0.8' in package repositories
Error: failed to retrieve package 'dplyr@1.0.8'
 <<snip traceback>>
Traceback (most recent calls last):
14: renv::restore(prompt = FALSE)
13: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
12: retrieve(packages)
11: handler(package, renv_retrieve_impl(package))
<< snip >>
Execution halted
trying URL 'https://github.com/ohdsi/CharacterizationModule/archive/refs/tags/v0.2.3.zip'
Content type 'application/zip' length unknown
downloaded 22 KB
``` 
As you can see, it soldiers on after these "halted" steps, and trys the next one in the list. This results in a repeat of these messages over and over. As each module has similar dependencies, they're all the same.

Let me know if I can provide anything else for you

**Comment by anthonysena** [comment]
Thanks @DrTTrousers - I'm going to put this issue on hold while I get a non-Windows environment to test out. I really appreciate you digging into this issue and hopefully I'll get it sorted out in an upcoming release. For now, I'm going to move this issue to the next milestone so we can continue the investigation. Thanks!

**Comment by anthonysena** [comment]
Coming back to this after some time and just noting that I've added additional `keyring` configuration for Linux to the README based on site feedback during the SOS challenge. Additionally, Strategus will now load specific libraries (i.e. keyring) from the base R library as this is necessary when running using `renv::run`. I'll close this out but if the trouble persists after the v0.1.0 release we can revisit this.

**Comment by DrTTrousers** [comment]
Can confirm that it works, I've got Strategus working brilliantly now. Even from scratch!
