### ISSUE TITLE
generateNegativeControlOutcomeCohorts does not pass tempEmulationSchema properly

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Strategus#76]
`generateNegativeControlOutcomeCohorts` has a parameter to set the `tempEmulationSchema` but it is not properly passed to the `insertTable` function:

https://github.com/OHDSI/CohortGenerator/blob/30fe75d61cc8414f6021786502410fe7f66a3ac2/R/NegativeControlCohorts.R#L132-L143

**Comment by anthonysena** [comment]
@ablack3 I believe the root cause of this issue is in Strategus so I moved the issue to reflect this. I've made an update on the `sos-challenge` branch [here](https://github.com/OHDSI/Strategus/commit/a147a57f33fb6104edaf5dcbfadcf67bd596e3cb) which now allows for the specification of the `tempEmulationSchema` in the executionSettings and then properly sets the `options()` when running the module. I think this should resolve the problem you faced on GBQ if you'd like to test out running on the `sos-challenge` branch of Strategus?

**Comment by ablack3** [comment]
Awesome. I'll test it.

**Comment by ablack3** [comment]
I installed the "sos-challenge" branch and reran the study. I confirmed that I was using the new version of the code. I still get the same error however. 

@anthonysena Do you have the ability to test your modules on bigquery? There is a community bigquery test database you can use.

<img width="1111" alt="image" src="https://github.com/OHDSI/Strategus/assets/10227522/ed424c7c-6562-4565-bd04-1ba8db6bdf98">

**Comment by TomWhite-MedStar** [comment]
@anthonysena or @ablack3 , is there a way to get `options(sqlRenderTempEmulationSchema =  "main.scratch")` to apply globally across all Strategus modules if it is set in StrategusCodeToRun.R?
At present, that doesn't seem to work.  When I apply that option in StrategusCodeToRun, it seems to get reset each time `library(DatabaseConnector)` is called (even though I updated renv.lock to always use the same version of DatabaseConnector so that connections work consistently for Databricks).

**Comment by anthonysena** [comment]
@TomWhite-MedStar I thought this was addressed in the sos-challenge branch but per @ablack3 comment it appears to remain an open issue. @ablack3 not sure if you had any luck getting past this problem on a fork of Strategus?

**Comment by ablack3** [comment]
I don't think I did get past this issue using the fork. It's been a few weeks so I don't remember exactly but I think this is still an issue.

**Comment by anthonysena** [comment]
This is now fixed on `develop` and will be part of the v0.1.0 release. Per [this change](https://github.com/OHDSI/Strategus/blob/develop/R/Settings.R#L136), the `tempEmulationSchema` is explicitly stored in the execution settings.

**Comment by DrTTrousers** [comment]
Just to stir this pot again: the tempEmulationSchema is not properly passed through to cohort generator for any cohort either, its still neccessary to put the options(sqlRenderTempEmulationSchema) into the Main.R of each module.

**Comment by anthonysena** [comment]
Re-opening so that we can explictly add this option to the default script so you don't have to hack the Main.R
